#ifndef K_VENENUM_H
#define K_VENENUM_H
#define GUILDEQ "/wizards/venenum/guildeq/guildeq.c"
#define GUILDARM "/wizards/venenum/guildeq/guildarm.c"
#define GUILDARMOUR "/wizards/venenum/guildeq/armour.c"
#define GUILDBELT "/wizards/venenum/guildeq/belt.c"
#define GUILDBODYARMOUR "/wizards/venenum/guildeq/bodyarmour.c"
#define GUILDBOOTS "/wizards/venenum/guildeq/boots.c"
#define GUILDBRACELET "/wizards/venenum/guildeq/bracelet.c"
#define GUILDBRACERS "/wizards/venenum/guildeq/bracers.c"
#define GUILDCLOAK "/wizards/venenum/guildeq/cloak.c"
#define GUILDGLOVES "/wizards/venenum/guildeq/gloves.c"
#define GUILDHELMET "/wizards/venenum/guildeq/helmet.c"
#define GUILDLEGGINGS "/wizards/venenum/guildeq/leggings.c"
#define GUILDMASK "/wizards/venenum/guildeq/MASK.c"
#define GUILDNECKLACE "/wizards/venenum/guildeq/necklace.c"
#define GUILDPANTS "/wizards/venenum/guildeq/pants.c"
#define GUILDSHIELD "/wizards/venenum/guildeq/shield.c"
#define GUILDTUNIC "/wizards/venenum/guildeq/tunic.c"
#define GUILDVEST "/wizards/venenum/guildeq/vest.c"
#define GUILDWEP "/wizards/venenum/guildeq/guildwep.c"
#endif
